# Generated by Django 4.2.7 on 2024-05-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Formulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=256, verbose_name="Nombre")),
                ("fecha", models.DateField(verbose_name="Fecha")),
                (
                    "remision",
                    models.CharField(
                        choices=[
                            ("No remitido", "No remitido"),
                            ("Atención primaria", "Atención primaria"),
                            ("Programa de control", "Programa de control"),
                            ("Atención secundaria", "Atención secundaria"),
                        ],
                        max_length=256,
                        verbose_name="REMISIÓN",
                    ),
                ),
                (
                    "historia_clinica",
                    models.BooleanField(
                        default=True, verbose_name="Diagnóstico histológico"
                    ),
                ),
                (
                    "motivo_consulta",
                    models.CharField(
                        default="No motivo de consulta",
                        max_length=256,
                        verbose_name="Motivo de consulta",
                    ),
                ),
                (
                    "primer_sintoma",
                    models.CharField(max_length=256, verbose_name="Primer síntoma"),
                ),
                (
                    "tiempo_de_aparicion",
                    models.CharField(
                        choices=[
                            ("Días", "Días"),
                            ("Meses", "Meses"),
                            ("Años", "Años"),
                        ],
                        max_length=256,
                        verbose_name="Tiempo de aparición",
                    ),
                ),
                (
                    "otros_sintomas",
                    models.TextField(
                        blank=True, null=True, verbose_name="Otros Síntomas"
                    ),
                ),
                (
                    "personales_de_riesgo",
                    models.CharField(
                        choices=[
                            ("Ninguno", "Ninguno"),
                            ("Tabaquismo", "Tabaquismo"),
                            ("Exposición a irritantes", "Exposición a irritantes"),
                            (
                                "Ingestión bebidas alcohólicas",
                                "Ingestión bebidas alcohólicas",
                            ),
                            (
                                "Trauma región de la lesión",
                                "Trauma región de la lesión",
                            ),
                            ("Mala higiene bucal", "Mala higiene bucal"),
                            ("Uso de prótesis", "Uso de prótesis"),
                        ],
                        max_length=256,
                        verbose_name="Antecedentes personales de riesgos",
                    ),
                ),
                (
                    "personales_patologicos",
                    models.CharField(
                        choices=[
                            ("Ninguno", "Ninguno"),
                            ("Leucoplasias", "Leucoplasias"),
                            ("Queratosis", "Queratosis"),
                            ("Avitaminosis", "Avitaminosis"),
                            ("Tuberculosis", "Tuberculosis"),
                            ("Sífilis", "Sífilis"),
                            ("Infección crónica", "Infección crónica"),
                            ("VIH", "VIH"),
                            ("Neoplasia maligna", "Neoplasia maligna"),
                        ],
                        max_length=256,
                        verbose_name="Antevedentes personales patológicos",
                    ),
                ),
                (
                    "familiares_con_cancer",
                    models.CharField(
                        choices=[
                            ("Si", "Si"),
                            ("No", "No"),
                            ("Desconocido", "Desconocido"),
                        ],
                        max_length=256,
                        verbose_name="Familiares con cáncer",
                    ),
                ),
                (
                    "caracteristicas_de_la_lesion",
                    models.CharField(
                        choices=[
                            ("Vegetante", "Vegetante"),
                            ("Infiltrante", "Infiltrante"),
                            ("Úlcero-vegetante", "Úlcero-vegetante"),
                            ("Úlcero-infiltrante", "Úlcero-infiltrante"),
                            ("Necrosante", "Necrosante"),
                            ("Plana", "Plana"),
                            ("Submucosa", "Submucosa"),
                            ("Nodular", "Nodular"),
                        ],
                        max_length=256,
                        verbose_name="Características de la lesión",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("Derecha", "Derecha"),
                            ("Central", "Central"),
                            ("Izquierda", "Izquierda"),
                        ],
                        max_length=256,
                        verbose_name="Región",
                    ),
                ),
                (
                    "tamanno_de_la_lesion",
                    models.DateField(verbose_name="Tamaño de la lesión"),
                ),
                (
                    "localizacion_en_labio",
                    models.CharField(
                        choices=[
                            ("Labio superior", "Labio superior"),
                            ("Mucosa superior", "Mucosa superior"),
                            ("Comisuras labiales", "Comisuras labiales"),
                            ("Labio inferior", "Labio inferior"),
                            ("Mucosa inferior", "Mucosa inferior"),
                        ],
                        max_length=256,
                        verbose_name="Localización (Labio)",
                    ),
                ),
                (
                    "lengua_movil",
                    models.CharField(
                        choices=[
                            ("Cara central", "Cara central"),
                            ("Cara dorsal", "Cara dorsal"),
                            ("Punta", "Punta"),
                            ("Borde", "Borde"),
                        ],
                        max_length=256,
                        verbose_name="Lengua móvil",
                    ),
                ),
                (
                    "suelo_de_Boca",
                    models.CharField(
                        choices=[
                            ("Parte anterior", "Parte anterior"),
                            ("Parte lateral", "Parte lateral"),
                        ],
                        max_length=256,
                        verbose_name="Suelo de Boca",
                    ),
                ),
                (
                    "encia",
                    models.CharField(
                        choices=[("Superior", "Superior"), ("Inferior", "Inferior")],
                        max_length=256,
                        verbose_name="Encía",
                    ),
                ),
                (
                    "otras_partes_del_a_boca",
                    models.CharField(
                        choices=[
                            ("Carrillo", "Carrillo"),
                            ("Vesíbulo", "Vesíbulo"),
                            ("Paladar duro", "Paladar duro"),
                            ("Espacio retromolar", "Espacio retromolar"),
                        ],
                        max_length=256,
                        verbose_name="Otras Partes (Boca)",
                    ),
                ),
                (
                    "glandulas_salibales",
                    models.CharField(
                        choices=[
                            ("Parótida", "Parótida"),
                            ("Sublingual", "Sublingual"),
                            ("Submaxilar", "Submaxilar"),
                            ("Otra", "Otra"),
                        ],
                        max_length=256,
                        verbose_name="Glándulas salivales",
                    ),
                ),
                (
                    "ardenopatia_cervical_derecha",
                    models.CharField(
                        choices=[
                            ("No", "No"),
                            ("Nivel I", "Nivel I"),
                            ("Nivel II", "Nivel II"),
                            ("Nivel III", "Nivel III"),
                            ("Nivel IV", "Nivel IV"),
                            ("Nivel V", "Nivel V"),
                        ],
                        max_length=256,
                        verbose_name="Ardenopatía cervical derecha",
                    ),
                ),
                (
                    "ardenopatia_cervical_izquierda",
                    models.CharField(
                        choices=[
                            ("No", "No"),
                            ("Nivel I", "Nivel I"),
                            ("Nivel II", "Nivel II"),
                            ("Nivel III", "Nivel III"),
                            ("Nivel IV", "Nivel IV"),
                            ("Nivel V", "Nivel V"),
                        ],
                        max_length=256,
                        verbose_name="Ardenopatía cervical izquierda",
                    ),
                ),
                (
                    "extension_clinica_a",
                    models.CharField(
                        choices=[
                            ("No", "No"),
                            ("Suelo de boca", "Suelo de boca"),
                            ("Laringe", "Laringe"),
                            ("Labio", "Labio"),
                            (
                                "Otras partes de la cavidad oral",
                                "Otras partes de la cavidad oral",
                            ),
                            ("Mesofaringe", "Mesofaringe"),
                            ("Hipofaringe", "Hipofaringe"),
                            ("Encía", "Encía"),
                            ("Nasofaringe", "Nasofaringe"),
                            ("Piel y partes blandas", "Piel y partes blandas"),
                            ("Hueso", "Hueso"),
                            ("Otras", "Otras"),
                        ],
                        max_length=256,
                        verbose_name="Extensión clínica a",
                    ),
                ),
                (
                    "performance_status",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                        ],
                        max_length=256,
                        verbose_name="Performance status",
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=256, verbose_name="Primer apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(max_length=256, verbose_name="Segundo apellido"),
                ),
                (
                    "nombre_del_paciente",
                    models.CharField(
                        max_length=256, verbose_name="Nombre del paciente"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("Femenino", "Femenino"), ("Masculino", "Masculino")],
                        max_length=256,
                        verbose_name="Sexo",
                    ),
                ),
                ("edad", models.PositiveIntegerField(verbose_name="Edad (en años)")),
                (
                    "color_de_piel",
                    models.CharField(
                        choices=[
                            ("Blanca", "Blanca"),
                            ("Negra", "Negra"),
                            ("Mestiza", "Mestiza"),
                        ],
                        max_length=256,
                        verbose_name="Color de la piel",
                    ),
                ),
                (
                    "carne_de_identidad",
                    models.CharField(max_length=256, verbose_name="Carné de identidad"),
                ),
                (
                    "historia_clinica_numero",
                    models.CharField(
                        max_length=256, verbose_name="Historia clínica número:"
                    ),
                ),
                (
                    "fecha_de_inscripcion",
                    models.PositiveIntegerField(verbose_name="Fecha de Inscripción"),
                ),
                (
                    "creatinina",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Creatinina"
                    ),
                ),
                (
                    "hemoglobina",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Hemoglobina"
                    ),
                ),
                (
                    "imagen_rx_torax",
                    models.CharField(
                        choices=[
                            ("Ninguno", "Ninguno"),
                            ("Positivo", "Positivo"),
                            ("Negativo", "Negativo"),
                        ],
                        max_length=256,
                        verbose_name="Imagen del Torax",
                    ),
                ),
                (
                    "imagen_us_abdomen",
                    models.CharField(
                        choices=[
                            ("Ninguno", "Ninguno"),
                            ("Positivo", "Positivo"),
                            ("Negativo", "Negativo"),
                        ],
                        max_length=256,
                        verbose_name="Imagen del Abdomen",
                    ),
                ),
                (
                    "imagen_tac_cavidad_oral",
                    models.CharField(
                        choices=[
                            ("Ninguno", "Ninguno"),
                            ("Positivo", "Positivo"),
                            ("Negativo", "Negativo"),
                        ],
                        max_length=256,
                        verbose_name="Imagen de la Cavidad Oral",
                    ),
                ),
                (
                    "otros_tac_faringe",
                    models.CharField(
                        choices=[
                            ("Ninguno", "Ninguno"),
                            ("Positivo", "Positivo"),
                            ("Negativo", "Negativo"),
                        ],
                        max_length=256,
                        verbose_name="Otros TAC Faringe",
                    ),
                ),
                (
                    "otros_tac_cuello",
                    models.CharField(
                        choices=[
                            ("Ninguno", "Ninguno"),
                            ("Positivo", "Positivo"),
                            ("Negativo", "Negativo"),
                        ],
                        max_length=256,
                        verbose_name="Otros TAC Cuello",
                    ),
                ),
                (
                    "otros_tac_torax",
                    models.CharField(
                        choices=[
                            ("Ninguno", "Ninguno"),
                            ("Positivo", "Positivo"),
                            ("Negativo", "Negativo"),
                        ],
                        max_length=256,
                        verbose_name="Otros TAC Tórax",
                    ),
                ),
                (
                    "otros_rmn",
                    models.CharField(
                        choices=[
                            ("Ninguno", "Ninguno"),
                            ("Positivo", "Positivo"),
                            ("Negativo", "Negativo"),
                        ],
                        max_length=256,
                        verbose_name="Otros RMN",
                    ),
                ),
                (
                    "biopsia_numero",
                    models.PositiveIntegerField(verbose_name="Biopsia No"),
                ),
                (
                    "fecha_de_diagnostico",
                    models.DateField(verbose_name="Fecha de diagnóstico"),
                ),
                (
                    "diagnostico_topografico",
                    models.CharField(
                        max_length=256, verbose_name="Diagnóstico Topográfico"
                    ),
                ),
            ],
            options={
                "verbose_name": "Formulario",
                "verbose_name_plural": "Formularios",
            },
        ),
    ]
