# Generated by Django 4.2.7 on 2024-05-26 00:48

import apps.formulario.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="formulario",
            name="firma_del_medico",
        ),
        migrations.AlterField(
            model_name="formulario",
            name="biopsia_numero",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Biopsia No",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="carne_de_identidad",
            field=models.CharField(
                max_length=11,
                validators=[django.core.validators.RegexValidator("^[0-9]+$")],
                verbose_name="Carné de identidad",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="creatinina",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Creatinina",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="cual_tratamiento",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Cuál tratamiento"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="fecha_de_inscripcion",
            field=models.DateField(verbose_name="Fecha de inscripcion"),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="hemoglobina",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Hemoglobina",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="historia_clinica_numero",
            field=models.PositiveIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Historia Clínica No",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="inclusion_en_ec",
            field=models.BooleanField(default=False, verbose_name="Inclusión en EC"),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="nombre",
            field=models.CharField(max_length=256, unique=True, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="nombre_del_paciente",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$"),
                    apps.formulario.models.validate_noVacio,
                ],
                verbose_name="Nombre del paciente",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="observaciones",
            field=models.TextField(blank=True, null=True, verbose_name="Observaciones"),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="otras",
            field=models.TextField(
                blank=True,
                help_text=" En csao de seleccionar Otras rellene este campo",
                null=True,
                verbose_name="Otras",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="otro_tratamiento",
            field=models.BooleanField(default=False, verbose_name="Otro tratamiento"),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="otro_tratamiento_planificado",
            field=models.TextField(
                blank=True,
                help_text=" En csao de seleccionar Otro rellene este campo",
                null=True,
                verbose_name="Que otro tratamiento se aplicó",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="primer_apellido",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$"),
                    apps.formulario.models.validate_noVacio,
                ],
                verbose_name="Primer apellido",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="registro_profesional",
            field=models.CharField(
                max_length=4,
                validators=[django.core.validators.RegexValidator("^[0-9]{4}$")],
                verbose_name="Registro profesional",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="segundo_apellido",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$"),
                    apps.formulario.models.validate_noVacio,
                ],
                verbose_name="Segundo apellido",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="tratamiento_quimioterapia",
            field=models.BooleanField(
                default=False, verbose_name="Tratamiento quimioterapia"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="tratamiento_quirurgico",
            field=models.BooleanField(
                default=False, verbose_name="Tratamiento quirúrgico"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="tratamiento_radioterapia",
            field=models.BooleanField(
                default=False, verbose_name="Tratamiento radioterapia"
            ),
        ),
    ]
