# Generated by Django 4.2.7 on 2024-05-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formulario", "0002_remove_formulario_firma_del_medico_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="dosis_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="Gosis totaD",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="esquema_tratamiento",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Esquema del tratamiento",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="fecha_del_final_del_tratamiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del final del tratamiento"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="fecha_del_final_del_tratamiento_quimioterapeutico",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha del final del tratamiento quimioterapeutico",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="fecha_del_final_del_tratamiento_radioterapeutico",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha del final del tratamiento radioterapeutico",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="fecha_del_inicio_del_tratamiento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del inicio del tratamiento"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="fecha_del_inicio_del_tratamiento_quimioterapeutico",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha del inicio del tratamiento quimioterapeutico",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="fecha_del_inicio_del_tratamiento_radioterapeutico",
            field=models.DateField(
                blank=True,
                null=True,
                verbose_name="Fecha del inicio del tratamiento radioterapeutico",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="fecha_del_tratamiento_quirurgico",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha del tratamiento"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="gy_fraccion",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                max_digits=15,
                null=True,
                verbose_name="GY fracción",
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="numero_de_ciclos",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="No de ciclos"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="tipo_de_cirugia",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tipo de cirugía"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="tipo_de_tratamiento_radioterap",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="Tipo de tratamiento radioterapeutico",
            ),
        ),
    ]
