# Generated by Django 4.2.7 on 2024-06-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formulario", "0003_alter_formulario_dosis_total_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formulario",
            old_name="diagnostico_en",
            new_name="diagnosticado_en",
        ),
        migrations.RenameField(
            model_name="formulario",
            old_name="diagnostico_en_selecciona",
            new_name="diagnosticado_en_selecciona",
        ),
        migrations.AlterField(
            model_name="formulario",
            name="metastasis_a_distancia",
            field=models.CharField(
                choices=[
                    ("Desconocida", "Desconocida"),
                    ("Ninguna", "Ninguna"),
                    ("Pulmón pleura", "Pulmón pleura"),
                    ("Hígado", "Hígado"),
                    ("Ovarios", "Ovarios"),
                    ("Hueso", "Hueso"),
                    ("Ganglios distales", "Ganglios distales"),
                    ("Cerebro", "Cerebro"),
                    ("Piel y TCS", "Piel y TCS"),
                ],
                max_length=256,
                verbose_name="c",
            ),
        ),
    ]
