# Generated by Django 4.2.7 on 2024-06-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0004_rename_diagnostico_en_formulario_diagnosticado_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="formulario",
            name="ptnm_pM",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="TNM pM"
            ),
        ),
        migrations.AddField(
            model_name="formulario",
            name="ptnm_pN",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="TNM pN"
            ),
        ),
        migrations.AddField(
            model_name="formulario",
            name="ptnm_pT",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="TNM pT"
            ),
        ),
        migrations.AddField(
            model_name="formulario",
            name="tnm_M",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="TNM M"
            ),
        ),
        migrations.AddField(
            model_name="formulario",
            name="tnm_N",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="TNM N"
            ),
        ),
        migrations.AddField(
            model_name="formulario",
            name="tnm_T",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="TNM T"
            ),
        ),
        migrations.AlterField(
            model_name="formulario",
            name="metastasis_a_distancia",
            field=models.CharField(
                choices=[
                    ("Desconocida", "Desconocida"),
                    ("Ninguna", "Ninguna"),
                    ("Pulmón pleura", "Pulmón pleura"),
                    ("Hígado", "Hígado"),
                    ("Ovarios", "Ovarios"),
                    ("Hueso", "Hueso"),
                    ("Ganglios distales", "Ganglios distales"),
                    ("Cerebro", "Cerebro"),
                    ("Piel y TCS", "Piel y TCS"),
                ],
                max_length=256,
                verbose_name="Metástasis a distancia",
            ),
        ),
    ]
