# Generated by Django 4.2.7 on 2024-06-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "formulario",
            "0006_rename_motivo_de_consulta_formulario_motivo_consulta_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="formulario",
            name="en_caso_de_si",
            field=models.CharField(
                blank=True,
                max_length=256,
                null=True,
                verbose_name="En caso de ser sí; cuál es el código",
            ),
        ),
    ]
